# Generated by Django 4.2.3 on 2023-07-15 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_kor', models.CharField(max_length=30)),
                ('title_eng', models.TextField(default='')),
                ('poster_url', models.URLField(max_length=1024)),
                ('rating_aud', models.CharField(max_length=10)),
                ('rating_cri', models.CharField(max_length=10)),
                ('rating_net', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=20)),
                ('showtimes', models.CharField(max_length=30)),
                ('release_date', models.TextField(default='')),
                ('rate', models.CharField(max_length=20)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('image_url', models.URLField(max_length=1024)),
                ('movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
