# Generated by Django 4.2.3 on 2023-07-14 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=30)),
                ('title_eng', models.CharField(max_length=30)),
                ('poster_url', models.URLField(max_length=1024)),
                ('rating_aud', models.CharField(max_length=10)),
                ('rating_cri', models.CharField(max_length=10)),
                ('rating_net', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=20)),
                ('showtimes', models.CharField(max_length=30)),
                ('release_date', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=20)),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('image_url', models.URLField(max_length=1024)),
                ('movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='movie.movie')),
            ],
        ),
    ]
